// ── Schema DSL ──────────────────────────────────────────────────────────────
//
// Design rules (Phase 2.5 ergonomics refresh):
//
// 1. No magic strings. Anywhere a developer could type a literal string
//    referring to a schema element, the type system must know about it.
//    Column references come from `table.columnName` ref objects. Table
//    references come from the imported Table object. Enum values come from
//    the `enum` option on text/integer.
//
// 2. Zero boilerplate in the common case. Every non-primary-key column
//    defaults to `merge: 'lww'` — explicit opt-out via `{ merge: false }`.
//    View() takes just a table — no name argument; the name is inferred
//    from the object-property key at the `db.use({...})` call site.
//
// 3. Metadata lives under `$`-prefixed keys (`$tag`, `$name`, `$columns`,
//    `$record`) so the table object can also expose one `ColumnRef` per
//    column key at the top level without colliding with user-defined names.
//    Runtime guard rejects `$`-prefixed column names at `table()` construction.

/** Sentinel id_key for zero-group-by (global) aggregates — a single output row. */
import { errors, SchemaCode } from './errors';

export const GLOBAL_AGG_KEY = '$agg';

export type MergeStrategy = 'lww' | 'set_union' | 'max' | 'min' | 'add';

// ── Column definitions ────────────────────────────────────────────────────

/** 'value' is produced by `defineValue(...)` composite columns — stored
 *  as JSON-in-TEXT but tagged so the runtime can re-brand + re-validate
 *  on rehydration. Scalar value objects reuse the underlying primitive
 *  kind (text/integer/etc.) and carry `$valueRef` as the only marker.
 *  See `packages/core/src/value.ts`. */
export type ColumnKind = 'id' | 'integer' | 'real' | 'text' | 'boolean' | 'value';

export interface ColumnDef<T> {
    readonly $type: T;  // phantom — carries value type for inference only
    /** Coarse-grained tag of the JS value type. Distinguishes booleans
     *  from integers (both serialize to SQLite's INTEGER, so `sqlType`
     *  alone can't recover the JS shape). Used by entity state validators
     *  and any other consumer that needs the original constructor intent. */
    readonly kind: ColumnKind;
    readonly sqlType: string;
    readonly nullable: boolean;
    readonly primaryKey: boolean;
    /** null means "no merge strategy" (explicit opt-out or primary key). */
    readonly merge: MergeStrategy | null;
    /** Optional enum narrowing; purely a TS refinement, no SQLite effect. */
    readonly enum?: readonly T[];
    /** Optional default when the column is written without a value.
     *  Phase B2 — introduced alongside value-object column factories so
     *  `Money({ default: Money.usd(0) })` works; also used by primitive
     *  columns when a default is sensible (currently value-only). */
    readonly default?: T;
    /** Back-reference to the originating value-def, populated by
     *  `defineValue(...)` so parent composites + the entity runtime
     *  can recurse into nested values for validation / rehydration. */
    readonly $valueRef?: unknown;
}

/** Integer primary key — auto-generated by the store when `insert()` omits it. */
export function id(): ColumnDef<number> {
    return {
        $type: 0 as never,
        kind: 'id',
        sqlType: 'INTEGER PRIMARY KEY',
        nullable: false,
        primaryKey: true,
        merge: null,
    };
}

type NumericColumnOpts<E extends readonly number[] = never> = {
    merge?: MergeStrategy | false;
    enum?: E;
};

type TextColumnOpts<E extends readonly string[] = never> = {
    merge?: MergeStrategy | false;
    enum?: E;
};

type NumericEnumValue<E extends readonly number[]> = [E] extends [never] ? number : E[number];
type TextEnumValue<E extends readonly string[]> = [E] extends [never] ? string : E[number];

export function integer<E extends readonly number[] = never>(
    opts?: NumericColumnOpts<E>,
): ColumnDef<NumericEnumValue<E>> {
    return {
        $type: 0 as never,
        kind: 'integer',
        sqlType: 'INTEGER',
        nullable: false,
        primaryKey: false,
        merge: resolveMerge(opts?.merge),
        enum: opts?.enum as readonly NumericEnumValue<E>[] | undefined,
    };
}

export function real(opts?: { merge?: MergeStrategy | false }): ColumnDef<number> {
    return {
        $type: 0 as never,
        kind: 'real',
        sqlType: 'REAL',
        nullable: false,
        primaryKey: false,
        merge: resolveMerge(opts?.merge),
    };
}

export function text<E extends readonly string[] = never>(
    opts?: TextColumnOpts<E>,
): ColumnDef<TextEnumValue<E>> {
    return {
        $type: '' as never,
        kind: 'text',
        sqlType: 'TEXT',
        nullable: false,
        primaryKey: false,
        merge: resolveMerge(opts?.merge),
        enum: opts?.enum as readonly TextEnumValue<E>[] | undefined,
    };
}

export function boolean(opts?: { merge?: MergeStrategy | false }): ColumnDef<boolean> {
    return {
        $type: false as never,
        kind: 'boolean',
        sqlType: 'INTEGER',
        nullable: false,
        primaryKey: false,
        merge: resolveMerge(opts?.merge),
    };
}

/**
 * Non-PK columns default to `'lww'`. `{ merge: false }` explicitly opts out.
 * PK columns ignore the merge option (set to `null`).
 */
function resolveMerge(merge: MergeStrategy | false | undefined): MergeStrategy | null {
    if (merge === false) return null;
    return merge ?? 'lww';
}

// ── Type helpers ──────────────────────────────────────────────────────────

type InferType<C> = C extends ColumnDef<infer T> ? T : never;

export type InferRecord<C extends Record<string, ColumnDef<unknown>>> = {
    [K in keyof C]: InferType<C[K]>;
};

/** Keys of a record whose value type is `number`. Used to constrain
 * aggregate helpers (`sum`, `avg`, etc.) to numeric columns at compile time. */
export type NumericKeys<T> = {
    [K in keyof T]: T[K] extends number ? K : never;
}[keyof T];

// ── Column references ────────────────────────────────────────────────────
//
// A ColumnRef is a lightweight, typed handle to a specific column of a
// specific table. The phantom `$valueType` carries the column's value type
// so view operators can constrain themselves structurally:
//
//     sum(expenses.amount)     // ✓ amount is number
//     sum(expenses.category)   // ✗ category is string
//     topN(expenses.amount, 5) // ✓ sortable numeric column
//
// At runtime a ColumnRef is `{ $tag: 'col', $table, $name }`. The value
// type is erased — the rest of the pipeline only needs the column name.

export interface ColumnRef<TName extends string, K extends string, T> {
    readonly $tag: 'col';
    readonly $table: TName;
    readonly $name: K;
    readonly $valueType: T;  // phantom
}

/** Extract the column name whether `x` is a string or a ColumnRef. */
function refOrString(x: string | ColumnRef<string, string, unknown>): string {
    return typeof x === 'string' ? x : x.$name;
}

// ── Table definition ──────────────────────────────────────────────────────
//
// A Table is an intersection of:
//   - metadata under $-prefixed keys (`$tag`, `$name`, `$columns`, `$record`)
//   - one ColumnRef per user-defined column key at the top level
//
// So `expenses.amount` is a ColumnRef, `expenses.$columns.amount` is the
// underlying ColumnDef, and `expenses.$name` is the literal table name.
//
// `AnyTable` is the "structural base" used in function signatures that
// accept any table. Without it, writing `Table<string, Record<string,
// ColumnDef<unknown>>>` collapses the column-ref index type into a string
// index signature that conflicts with the literal-typed metadata fields.

export interface TableMetadata<
    TName extends string = string,
    TCols extends Record<string, ColumnDef<unknown>> = Record<string, ColumnDef<unknown>>,
> {
    readonly $tag: 'table';
    readonly $name: TName;
    readonly $columns: TCols;
    readonly $record: InferRecord<TCols>;
    readonly $idKey: keyof TCols & string;
}

export type Table<
    TName extends string,
    TCols extends Record<string, ColumnDef<unknown>>,
> = TableMetadata<TName, TCols> & {
    readonly [K in keyof TCols & string]: ColumnRef<TName, K, InferType<TCols[K]>>;
};

/** Structural base for "any table". Use this in function signatures that
 *  accept any Table — the full intersection type breaks down when TCols
 *  is a string-indexed `Record<string, ColumnDef<unknown>>`. */
export type AnyTable = TableMetadata;

export function table<
    TName extends string,
    TCols extends Record<string, ColumnDef<unknown>>,
>(
    name: TName,
    columns: TCols,
): Table<TName, TCols> {
    // Runtime guard: column keys must not collide with $-prefixed metadata.
    for (const key of Object.keys(columns)) {
        if (key.startsWith('$')) {
            throw errors.schema(SchemaCode.INVALID_COLUMN_NAME, {
                message:
                    `Invalid column name '${key}' in table '${name}': column names ` +
                    `may not start with '$' (reserved for table metadata).`,
                hint: `Rename the column to remove the '$' prefix.`,
                context: { table: name, column: key },
            });
        }
    }

    // Find the primary key.
    const idKeyEntry = Object.entries(columns).find(([, col]) => col.primaryKey);
    if (!idKeyEntry) {
        throw errors.schema(SchemaCode.MISSING_PRIMARY_KEY, {
            message: `Table '${name}' has no primary key column.`,
            hint: `Add id() for an auto-generated integer PK:\n\n  const ${name} = table('${name}', { id: id(), ... })`,
            context: { table: name },
        });
    }
    const idKey = idKeyEntry[0];

    // Build the intersection object: metadata + one ColumnRef per column key.
    const metadata = {
        $tag: 'table' as const,
        $name: name,
        $columns: columns,
        $record: undefined as never,
        $idKey: idKey as keyof TCols & string,
    };

    const refs: Record<string, ColumnRef<TName, string, unknown>> = {};
    for (const colName of Object.keys(columns)) {
        refs[colName] = {
            $tag: 'col',
            $table: name,
            $name: colName,
            $valueType: undefined as never,
        };
    }

    return { ...metadata, ...refs } as Table<TName, TCols>;
}

// ── Aggregate helpers ─────────────────────────────────────────────────────

export interface AggDef {
    readonly fn: 'sum' | 'count' | 'avg' | 'min' | 'max';
    readonly field: string;
}

// Overloads: each numeric aggregate accepts either a ColumnRef<_, _, number>
// or a string literal constrained to numeric keys of the implicit TRecord.
// The overload resolution hangs off the argument type at the call site.

export function sum<TName extends string, K extends string>(
    ref: ColumnRef<TName, K, number>,
): AggDef;
export function sum<T, K extends string & NumericKeys<T>>(field: K): AggDef;
export function sum(x: string | ColumnRef<string, string, number>): AggDef {
    return { fn: 'sum', field: refOrString(x) };
}

export function avg<TName extends string, K extends string>(
    ref: ColumnRef<TName, K, number>,
): AggDef;
export function avg<T, K extends string & NumericKeys<T>>(field: K): AggDef;
export function avg(x: string | ColumnRef<string, string, number>): AggDef {
    return { fn: 'avg', field: refOrString(x) };
}

export function min<TName extends string, K extends string>(
    ref: ColumnRef<TName, K, number>,
): AggDef;
export function min<T, K extends string & NumericKeys<T>>(field: K): AggDef;
export function min(x: string | ColumnRef<string, string, number>): AggDef {
    return { fn: 'min', field: refOrString(x) };
}

export function max<TName extends string, K extends string>(
    ref: ColumnRef<TName, K, number>,
): AggDef;
export function max<T, K extends string & NumericKeys<T>>(field: K): AggDef;
export function max(x: string | ColumnRef<string, string, number>): AggDef {
    return { fn: 'max', field: refOrString(x) };
}

export function count(): AggDef {
    return { fn: 'count', field: '*' };
}

// ── Operator wire format (matches the Rust DBSP engine) ──────────────────

export type Operator =
    | { op: 'filter'; field: string; eq: unknown }
    | { op: 'project'; fields: string[] }
    | { op: 'topN'; sort_by: string; limit: number; order: string }
    | { op: 'aggregate'; group_by: string[]; aggregates: Record<string, AggDef> }
    | { op: 'distinct'; key: string }
    | { op: 'join'; right_table: string; left_key: string; right_key: string };

// ── Monotonicity classification ───────────────────────────────────────────

export type Monotonicity = 'monotonic' | 'non_monotonic' | 'unknown';

function classifyPipeline(pipeline: Operator[]): Monotonicity {
    for (const op of pipeline) {
        if (op.op === 'topN' || op.op === 'distinct' || op.op === 'join') {
            return 'non_monotonic';
        }
    }
    return pipeline.length === 0 ? 'unknown' : 'monotonic';
}

// ── View builder ──────────────────────────────────────────────────────────
//
// view(sourceTable).filter(...).topN(...).aggregate(...)
//
// The name is assigned later by the store at registration time (derived
// from the object-property key at the `db.use({...})` call site). Internally
// each builder carries a generated `$id` so the store can look it up by
// reference equality, but users never see that id.

let viewIdCounter = 0;

export interface ViewBuilder<TRecord> {
    readonly $tag: 'view';
    readonly $id: string;
    readonly $tableName: string;
    /** Post-pipeline natural key. Single string for single-column keys,
     *  string array for composite keys (multi-column group-by aggregates). */
    readonly $idKey: string | string[];
    /** Source table's primary key — never rewritten by the pipeline. The
     *  worker uses it to dedup the join's `left_index`, which must key on
     *  source-row identity, not the post-aggregate group key. */
    readonly $sourceIdKey: string;
    readonly $pipeline: Operator[];
    readonly $sourceTables: string[];
    readonly $monotonicity: Monotonicity;
    readonly $record: TRecord;  // phantom

    filter<K extends string & keyof TRecord>(
        field: K | ColumnRef<string, K, TRecord[K]>,
        op: 'eq',
        value: TRecord[K],
    ): ViewBuilder<TRecord>;

    project<K extends string & keyof TRecord>(
        ...fields: (K | ColumnRef<string, K, TRecord[K]>)[]
    ): ViewBuilder<Pick<TRecord, K>>;

    topN<K extends string & NumericKeys<TRecord>>(
        sortBy: K | ColumnRef<string, K, number>,
        limit: number,
        order?: 'asc' | 'desc',
    ): ViewBuilder<TRecord>;

    aggregate<
        GK extends string & keyof TRecord,
        Aggs extends Record<string, AggDef>,
    >(
        groupBy: (GK | ColumnRef<string, GK, TRecord[GK]>)[],
        aggregates: Aggs,
    ): ViewBuilder<Pick<TRecord, GK> & { [K in keyof Aggs]: number }>;

    distinct(): ViewBuilder<TRecord>;

    join<
        RTable extends AnyTable,
        LK extends string & keyof TRecord,
        RK extends string & keyof RTable['$record'],
    >(
        rightTable: RTable,
        leftKey: LK | ColumnRef<string, LK, TRecord[LK]>,
        rightKey: RK | ColumnRef<string, RK, RTable['$record'][RK]>,
    ): ViewBuilder<TRecord & RTable['$record']>;
}

function createViewBuilder<TRecord>(
    $id: string,
    tableName: string,
    sourceIdKey: string,
    idKey: string | string[],
    pipeline: Operator[],
    sourceTables?: string[],
): ViewBuilder<TRecord> {
    const tables = sourceTables ?? [tableName];

    const builder = {
        $tag: 'view' as const,
        $id,
        $tableName: tableName,
        $idKey: idKey,
        $sourceIdKey: sourceIdKey,
        $pipeline: pipeline,
        $sourceTables: tables,
        $monotonicity: classifyPipeline(pipeline),
        $record: undefined as unknown as TRecord,

        filter<K extends string & keyof TRecord>(
            field: K | ColumnRef<string, K, TRecord[K]>,
            _op: 'eq',
            value: TRecord[K],
        ): ViewBuilder<TRecord> {
            return createViewBuilder<TRecord>($id, tableName, sourceIdKey, idKey, [
                ...pipeline,
                { op: 'filter', field: refOrString(field), eq: value },
            ], tables);
        },

        project<K extends string & keyof TRecord>(
            ...fields: (K | ColumnRef<string, K, TRecord[K]>)[]
        ): ViewBuilder<Pick<TRecord, K>> {
            return createViewBuilder<Pick<TRecord, K>>($id, tableName, sourceIdKey, idKey, [
                ...pipeline,
                { op: 'project', fields: fields.map(refOrString) },
            ], tables);
        },

        topN<K extends string & NumericKeys<TRecord>>(
            sortBy: K | ColumnRef<string, K, number>,
            limit: number,
            order: 'asc' | 'desc' = 'desc',
        ): ViewBuilder<TRecord> {
            return createViewBuilder<TRecord>($id, tableName, sourceIdKey, idKey, [
                ...pipeline,
                { op: 'topN', sort_by: refOrString(sortBy), limit, order },
            ], tables);
        },

        aggregate<
            GK extends string & keyof TRecord,
            Aggs extends Record<string, AggDef>,
        >(
            groupBy: (GK | ColumnRef<string, GK, TRecord[GK]>)[],
            aggregates: Aggs,
        ): ViewBuilder<Pick<TRecord, GK> & { [K in keyof Aggs]: number }> {
            const groupByNames = groupBy.map(refOrString);
            // Aggregate rewrites $idKey based on the group-by columns:
            //   - single column  → that column name (string)
            //   - multiple cols  → the column names (string[])
            //   - zero columns   → GLOBAL_AGG_KEY sentinel (single-row global aggregate)
            // $sourceIdKey is left untouched — join's left_index dedup needs
            // the source PK, not the post-aggregate group key.
            const aggIdKey: string | string[] = groupByNames.length === 1
                ? groupByNames[0]
                : groupByNames.length === 0
                    ? GLOBAL_AGG_KEY
                    : groupByNames;
            return createViewBuilder<Pick<TRecord, GK> & { [K in keyof Aggs]: number }>(
                $id, tableName, sourceIdKey, aggIdKey, [
                    ...pipeline,
                    { op: 'aggregate', group_by: groupByNames, aggregates },
                ], tables,
            );
        },

        distinct(): ViewBuilder<TRecord> {
            const distinctKey = Array.isArray(idKey) ? sourceIdKey : idKey;
            return createViewBuilder<TRecord>($id, tableName, sourceIdKey, idKey, [
                ...pipeline,
                { op: 'distinct', key: distinctKey },
            ], tables);
        },

        join<
            RTable extends AnyTable,
            LK extends string & keyof TRecord,
            RK extends string & keyof RTable['$record'],
        >(
            rightTable: RTable,
            leftKey: LK | ColumnRef<string, LK, TRecord[LK]>,
            rightKey: RK | ColumnRef<string, RK, RTable['$record'][RK]>,
        ): ViewBuilder<TRecord & RTable['$record']> {
            return createViewBuilder<TRecord & RTable['$record']>(
                $id, tableName, sourceIdKey, idKey, [
                    ...pipeline,
                    {
                        op: 'join',
                        right_table: rightTable.$name,
                        left_key: refOrString(leftKey),
                        right_key: refOrString(rightKey),
                    },
                ], [...tables, rightTable.$name],
            );
        },
    };

    return builder as ViewBuilder<TRecord>;
}

export function view<TTable extends AnyTable>(
    sourceTable: TTable,
): ViewBuilder<TTable['$record']> {
    const $id = `view_${++viewIdCounter}`;
    return createViewBuilder<TTable['$record']>(
        $id,
        sourceTable.$name,
        sourceTable.$idKey,
        sourceTable.$idKey,
        [],
    );
}

// ── Merge config extraction (used by store → worker INIT) ─────────────────

export function extractMergeConfig(
    t: AnyTable,
): { table: string; fields: Record<string, string> } | null {
    const fields: Record<string, string> = {};
    for (const [name, col] of Object.entries(t.$columns)) {
        if (col.merge !== null) {
            fields[name] = col.merge;
        }
    }
    if (Object.keys(fields).length === 0) return null;
    return { table: t.$name, fields };
}

// ── Runtime isType helpers (used by validateStoreConfig, etc.) ───────────

export function isTable(x: unknown): x is AnyTable {
    return typeof x === 'object' && x !== null && (x as { $tag?: string }).$tag === 'table';
}

export function isView(x: unknown): x is ViewBuilder<unknown> {
    return typeof x === 'object' && x !== null && (x as { $tag?: string }).$tag === 'view';
}
