export const SchemaCode = Object.freeze({
    MISSING_PRIMARY_KEY: 'MISSING_PRIMARY_KEY',
    RESERVED_COLUMN_PREFIX: 'RESERVED_COLUMN_PREFIX',
    INVALID_TABLE_NAME: 'INVALID_TABLE_NAME',
    DUPLICATE_TABLE_NAME: 'DUPLICATE_TABLE_NAME',
    DUPLICATE_VIEW_ID: 'DUPLICATE_VIEW_ID',
    DUPLICATE_CHANNEL_NAME: 'DUPLICATE_CHANNEL_NAME',
    VIEW_TABLE_NOT_FOUND: 'VIEW_TABLE_NOT_FOUND',
    CHANNEL_TABLE_NOT_FOUND: 'CHANNEL_TABLE_NOT_FOUND',
    INVALID_COLUMN_NAME: 'INVALID_COLUMN_NAME',
    INVALID_SQL_IDENTIFIER: 'INVALID_SQL_IDENTIFIER',
    INVALID_ENTITY_NAME: 'INVALID_ENTITY_NAME',
    INVALID_TOPIC_NAME: 'INVALID_TOPIC_NAME',
    INVALID_WORKFLOW_NAME: 'INVALID_WORKFLOW_NAME',
    INVALID_HEARTBEAT_NAME: 'INVALID_HEARTBEAT_NAME',
    INVALID_HEARTBEAT_INTERVAL: 'INVALID_HEARTBEAT_INTERVAL',
    INVALID_HEARTBEAT_CONFIG: 'INVALID_HEARTBEAT_CONFIG',
    DUPLICATE_HEARTBEAT_NAME: 'DUPLICATE_HEARTBEAT_NAME',
    HANDLER_NAME_RESERVED: 'HANDLER_NAME_RESERVED',
    HANDLER_NAME_INVALID: 'HANDLER_NAME_INVALID',
    HANDLER_NOT_FUNCTION: 'HANDLER_NOT_FUNCTION',
    STATE_FIELD_COLLISION: 'STATE_FIELD_COLLISION',
    TRANSITION_NOT_EXHAUSTIVE: 'TRANSITION_NOT_EXHAUSTIVE',
    TRANSITION_AMBIGUOUS: 'TRANSITION_AMBIGUOUS',
    TRANSITION_NO_MATCH: 'TRANSITION_NO_MATCH',
    UNKNOWN_MIGRATION_OP: 'UNKNOWN_MIGRATION_OP',
    CONFIG_LOAD_FAILED: 'CONFIG_LOAD_FAILED',
    CONFIG_NO_DEFAULT_EXPORT: 'CONFIG_NO_DEFAULT_EXPORT',
    NOT_ENTITY_DEFINITION: 'NOT_ENTITY_DEFINITION',
} as const);

export type SchemaCodeValue = typeof SchemaCode[keyof typeof SchemaCode];

export const EntityCode = Object.freeze({
    INVALID_TRANSITION: 'INVALID_TRANSITION',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
    TYPE_MISMATCH: 'TYPE_MISMATCH',
    ENUM_VIOLATION: 'ENUM_VIOLATION',
} as const);

export type EntityCodeValue = typeof EntityCode[keyof typeof EntityCode];

export const StoreCode = Object.freeze({
    INVALID_SEED_KEY: 'INVALID_SEED_KEY',
    INVALID_WORKSPACE_FORMAT: 'INVALID_WORKSPACE_FORMAT',
    INVALID_ENTITY_KEY: 'INVALID_ENTITY_KEY',
    WORKSPACE_NOT_ACTIVE: 'WORKSPACE_NOT_ACTIVE',
    RESET_DISABLED: 'RESET_DISABLED',
    TEST_STORE_ROW_NOT_FOUND: 'TEST_STORE_ROW_NOT_FOUND',
    TEST_STORE_UNKNOWN_TABLE: 'TEST_STORE_UNKNOWN_TABLE',
} as const);

export type StoreCodeValue = typeof StoreCode[keyof typeof StoreCode];

export const ConnectionCode = Object.freeze({
    NATS_UNREACHABLE: 'NATS_UNREACHABLE',
    RESTATE_UNREACHABLE: 'RESTATE_UNREACHABLE',
    AUTH_FAILED: 'AUTH_FAILED',
    WORKER_CRASHED: 'WORKER_CRASHED',
    HTTP_ERROR: 'HTTP_ERROR',
    MALFORMED_RESPONSE: 'MALFORMED_RESPONSE',
} as const);

export type ConnectionCodeValue = typeof ConnectionCode[keyof typeof ConnectionCode];

export const HandlerCode = Object.freeze({
    USER_HANDLER_ERROR: 'USER_HANDLER_ERROR',
    HANDLER_NOT_FOUND: 'HANDLER_NOT_FOUND',
    WORKFLOW_FAILED: 'WORKFLOW_FAILED',
} as const);

export type HandlerCodeValue = typeof HandlerCode[keyof typeof HandlerCode];

export const CliCode = Object.freeze({
    STACK_NOT_RUNNING: 'STACK_NOT_RUNNING',
    STACK_ALREADY_RUNNING: 'STACK_ALREADY_RUNNING',
    PORT_CONFLICT: 'PORT_CONFLICT',
    APP_DIR_NOT_FOUND: 'APP_DIR_NOT_FOUND',
    DEPENDENCY_NOT_FOUND: 'DEPENDENCY_NOT_FOUND',
    BUILD_OUTPUT_MISSING: 'BUILD_OUTPUT_MISSING',
    DIRECTORY_NOT_EMPTY: 'DIRECTORY_NOT_EMPTY',
    FRESH_REFUSED: 'FRESH_REFUSED',
    TIMEOUT: 'TIMEOUT',
    ENV_MISSING: 'ENV_MISSING',
    UNSUPPORTED_PLATFORM: 'UNSUPPORTED_PLATFORM',
    CHECKSUM_MISMATCH: 'CHECKSUM_MISMATCH',
    UNSUPPORTED_ARCHIVE: 'UNSUPPORTED_ARCHIVE',
    BINARY_NOT_FOUND: 'BINARY_NOT_FOUND',
    PROVIDER_MISSING: 'PROVIDER_MISSING',
} as const);

export type CliCodeValue = typeof CliCode[keyof typeof CliCode];
